url: ${SUB_URL}
path: data
port: 7890
allow_lan: true
api_port: 9090
secret: ${SECRET:-}
config_update_interval: ${CONFIG_UPDATE_INTERVAL:-3600}
github_proxy:
  - https://gh-proxy.org/
  - https://ghproxy.vip/
ui_url: ${UI_URL:-https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip}